// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://tlpzzneewikrpqfqygxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRscHp6bmVld2lrcnBxZnF5Z3hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjY4MTQsImV4cCI6MjA2MzkwMjgxNH0.hcW3ra_vsrA2eMPCe3LWFrGbuuhC_oadxXsS0bFDAg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);